# Netlify configuration file

[build]
  command = "chmod +x ./fix-dependencies.sh && ./fix-dependencies.sh && node ./netlify-esbuild-fix.js && chmod +x ./netlify-build.sh && ./netlify-build.sh"
  publish = "dist"
  
[build.processing]
  skip_processing = true

# Environment variable configuration
[build.environment]
  # Update to Node 18 to fix package compatibility issues
  NODE_VERSION = "18.18.0" 
  NPM_VERSION = "9.8.1"
  CI = "true"
  # Add environment variables to help with React issues
  VITE_CJS_IGNORE_WARNING = "true"
  NODE_OPTIONS = "--max-old-space-size=4096"
  
# All deploy contexts use the same command and settings
[context.production]
  command = "npm run build:netlify"

[context.deploy-preview]
  command = "npm run build:netlify"
  
[context.branch-deploy]
  command = "npm run build:netlify"
