[build]
  command = "npm run build"
  publish = "dist"
  
  [build.environment]
    # Disable secrets scanning for client-safe environment variables
    # These are meant to be public and included in the client bundle
    SECRETS_SCAN_ENABLED = "false"