# Netlify configuration file

[build]
  command = "chmod +x ./netlify-build.sh && ./netlify-build.sh"
  publish = "dist"
  
[build.processing]
  skip_processing = true

# Environment variable configuration
[build.environment]
  # Use Node 16 which has better compatibility with these libraries
  NODE_VERSION = "16.20.2" 
  NPM_VERSION = "8.19.4"
  CI = "true"
  # Add environment variables to help with React issues
  VITE_CJS_IGNORE_WARNING = "true"
  NODE_OPTIONS = "--max-old-space-size=4096"
  
# All deploy contexts use the same command and settings
[context.production]
  command = "npm run build:netlify"

[context.deploy-preview]
  command = "npm run build:netlify"
  
[context.branch-deploy]
  command = "npm run build:netlify"
